# Generated by Django 5.2 on 2025-06-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_portal_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
