# Generated by Django 5.2 on 2025-04-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_social_account_user_social_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_social_account',
        ),
    ]
