# Generated by Django 5.2 on 2025-05-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verceldeployment',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
