# Generated by Django 5.2 on 2025-05-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_verceldeployment_project_name'),
    ]

    operations = [
    ]
