# syntax=docker/dockerfile:1

FROM python:3.11-slim

WORKDIR /app

# Zaman dilimini ayarla (Europe/Istanbul)
ENV TZ=Europe/Istanbul
RUN apt-get update && apt-get install -y tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && rm -rf /var/lib/apt/lists/*

# Bağımlılıkları yükle
COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Proje dosyalarını kopyala
COPY . .

# Kullanıcı oluştur ve geçiş yap
RUN useradd -m myuser
USER myuser

# Ortam değişkenlerini ayarla
ENV DJANGO_SETTINGS_MODULE=core.settings.prod

# Gunicorn ile uygulamayı başlat
CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:$PORT core.wsgi:application || echo 'Gunicorn failed to start with exit code: $?' && sleep infinity"]