services:
  - type: web
    name: my-backend-app
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile.web
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.prod
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: my-backend-app.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://my-frontend-app.onrender.com
      - key: FRONTEND_URL
        value: https://my-frontend-app.onrender.com
      # PostgreSQL ayrı ayrı değişkenler
      - key: DB_HOST
        fromService:
          type: pserv
          name: SPA
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: SPA
          property: port
      - key: DB_NAME
        value: spa_ozqv
      - key: DB_USER
        value: spa_ozqv_user
      - key: DB_PASSWORD
        value: ylYFYpqwh9bbFTqOh5FjBVkAX2fB5KXi
      # Redis connection string
      - key: REDIS_URL
        fromService:
          type: redis
          name: spa-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: GITHUB_ACCESS_TOKEN
        sync: false
      - key: VERCEL_ACCESS_TOKEN
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        value: -ioxRFuknRekKP0zxxFTAfu5PZj6n0-jIOQ_yzyRxdw
      - key: LEMON_SQUEEZY_API_KEY
        sync: false
      - key: LEMON_SQUEEZY_STORE_ID
        sync: false
      - key: LEMON_SQUEEZY_WEBHOOK_SECRET
        sync: false
      - key: LEMON_SQUEEZY_CHECKOUT_URL
        sync: false

  - type: worker
    name: celery-worker
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile.worker
    preDeployCommand: "python manage.py migrate --settings=core.settings.prod"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.prod
      # PostgreSQL ayrı ayrı değişkenler
      - key: DB_HOST
        fromService:
          type: pserv
          name: SPA
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: SPA
          property: port
      - key: DB_NAME
        value: spa_ozqv
      - key: DB_USER
        value: spa_ozqv_user
      - key: DB_PASSWORD
        value: ylYFYpqwh9bbFTqOh5FjBVkAX2fB5KXi
      # Redis connection string
      - key: REDIS_URL
        fromService:
          type: redis
          name: spa-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LEMON_SQUEEZY_API_KEY
        sync: false
      - key: LEMON_SQUEEZY_STORE_ID
        sync: false
      - key: LEMON_SQUEEZY_WEBHOOK_SECRET
        sync: false
      - key: LEMON_SQUEEZY_CHECKOUT_URL
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://my-frontend-app.onrender.com

  - type: redis
    name: spa-redis
    region: oregon
    plan: starter

  - type: pserv
    name: SPA
    region: oregon
    plan: starter