# Generated by Django 5.2 on 2025-05-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='website',
            name='background_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='website',
            name='body_font',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='corner_radius',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='website',
            name='heading_font',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='website',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='website',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
