# Generated by Django 5.2 on 2025-05-26 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_websitedesignplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Hero Section'), ('about', 'About Section'), ('portfolio', 'Portfolio Section'), ('services', 'Services Section'), ('gallery', 'Gallery Section'), ('testimonials', 'Testimonials Section'), ('team', 'Team Section'), ('background', 'Background Image'), ('other', 'Other')], max_length=20)),
                ('prompt_used', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated/%Y/%m/%d/')),
                ('placeholder_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='spa.website')),
            ],
            options={
                'ordering': ['section', 'order_index'],
            },
        ),
    ]
