# Generated by Django 5.2 on 2025-05-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_generatedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
