# Generated by Django 5.2 on 2025-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_delete_generatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
