# Generated by Django 5.2 on 2025-05-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_website_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='short_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='website',
            name='website_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
