# Generated by Django 5.2 on 2025-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0008_website_short_description_website_website_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/%Y/%m/%d/'),
        ),
    ]
