# Generated by Django 5.2 on 2025-05-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_website_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='website',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='website',
            name='website_type',
        ),
    ]
