# Generated by Django 5.2 on 2025-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_remove_website_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='website_previews/%Y/%m/'),
        ),
    ]
