# Generated by Django 5.2 on 2025-05-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0011_website_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='preview_image',
        ),
    ]
