# Generated by Django 5.2 on 2025-06-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0012_remove_website_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='custom_styles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
