# Generated by Django 5.2 on 2025-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0013_website_custom_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='element_contents',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
