# Generated by Django 5.2 on 2025-06-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0014_website_element_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='business_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='website',
            name='original_user_prompt',
            field=models.TextField(blank=True),
        ),
    ]
