# Generated by Django 5.2 on 2025-06-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0015_website_business_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='website',
            name='custom_domain_verified',
            field=models.BooleanField(default=False),
        ),
    ]
